export const arrImg = [
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMkxf25IoY6qOV8au--HYelkTXA95K2Ythow&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_kJgDgamcVRvvpsRs-OnR_RGc5v85vtso2Q&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnWRH1qaWhOT7EkAGm7nCJXt9kk5F0o07I9Q&usqp=CA",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLRbFPIrBLo7v-iLExtLtT8qS6A1hec9thoQ&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyFFK3O1Jh1kPypVg2mF3GUJ-vLwTLwMuPxA&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTifiLVfahLpWiGY1X5FWpwAQid83MPTi4mPA&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKR2cLSBrr51t5__m-O2x114b0KvUr-xYYHA&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSd8emWC9LbxZHUuFCQztRiigLqr18FbzmBSA&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSv5gribrC-G5TtmEOOgFmraPcJWPIM1FH8OA&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSunlkqGSdP_Umz6J4RXbJplD6vIxM44aUxXQ&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSunlkqGSdP_Umz6J4RXbJplD6vIxM44aUxXQ&usqp=CAU",
];
export const arrCity = [
  "Минск",
  "Москва",
  "Питер",
  "Гродно",
  "Закопаны",
  "Краснодар",
  "Мурманск",
  "Петрозаводск",
  "Тула",
  "Камчатка",
  "Новосибирск",
];
